app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from app import db


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)

    users = db.relationship('User', backref='role')

    def __repr__(self):
        return '<Role {}>'.format(self.name)


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    def __repr__(self):
        return '<User {}>'.format(self.username)

    @property
    def password(self):
        raise AttributeError('password is no readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

app/main/forms.py
from flask.ext.wtf import FlaskForm
from wtforms import StringField, BooleanField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Email


class LoginForm(FlaskForm):
    email = StringField('Enter your email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])
    remember_me = BooleanField('remember_me', default=False)


class RegisterForm(FlaskForm):
    nickname = StringField('Enter your nickname', validators=[DataRequired()])
    email = StringField('Enter your email', validators=[DataRequired()])
    password = PasswordField('Set new Password', [
        DataRequired(),
        EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Repeat Password')

app/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.migrate import Migrate
from flask.ext.login import LoginManager
from flask.ext.bootstrap import Bootstrap
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask.ext.moment import Moment
from flask.ext.mail import Mail

from settings import config

db = SQLAlchemy()
mail = Mail()
bootstrap = Bootstrap()
moment = Moment()
toolbar = DebugToolbarExtension()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    toolbar.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# -*- coding: utf-8 -*-
from datetime import datetime

from flask import render_template, flash, redirect, url_for, g
from flask_login import login_required

from app import db
from app.auth.forms import RegisterForm
from . import main
from ..models import User


@main.route('/')
@main.route('/index')
@login_required
def index():
    user = g.user
    posts = [  # список выдуманных постов
        {
            'author': {'nickname': 'John'},
            'body': 'Beautiful day in Portland!'
        }, {
            'author': {'nickname': 'Susan'},
            'body': 'The Avengers movie was so cool!'
        }
    ]
    return render_template('index.html', **{
        'title': '',
        'user': user,
        'posts': posts,
        'current_time': datetime.utcnow(),
    })


@main.route('/registration', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            form.nickname.data,
            form.password.data,
            form.email.data,
        )
        db.session.add(user)
        db.session.commit()
        flash('User {} successfully added'.format(user))
        return redirect(url_for('index'))

    return render_template('register.html', **{
        'title': 'Registration in app',
        'form': form,
    })





@main.route('/user/<nickname>')
@login_required
def user(nickname):
    user = User.query.filter_by(nickname=nickname).first()
    if user == None:
        flash('User {} not found.'.format(nickname))
        return redirect(url_for('index'))
    posts = [
        { 'author': user, 'body': 'Test post #1' },
        { 'author': user, 'body': 'Test post #2' }
    ]
    return render_template('user.html',
                           user=user,
                           posts=posts)

app/views.py
# -*- coding: utf-8 -*-
from datetime import datetime

from app import app, db, models, lm
from flask import render_template, flash, redirect, url_for, g, session, request
from flask_login import current_user, login_required, login_user, logout_user

from app.forms import LoginForm, RegisterForm
from app.models import User


@lm.user_loader
def load_user(id):
    return User.query.get(int(id))


@app.before_request
def before_request():
    g.user = current_user


@app.route('/')
@app.route('/index')
@login_required
def index():
    user = g.user
    posts = [  # список выдуманных постов
        {
            'author': {'nickname': 'John'},
            'body': 'Beautiful day in Portland!'
        }, {
            'author': {'nickname': 'Susan'},
            'body': 'The Avengers movie was so cool!'
        }
    ]
    return render_template('index.html', **{
        'title': '',
        'user': user,
        'posts': posts,
        'current_time': datetime.utcnow(),
    })


@app.route('/registration', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            form.nickname.data,
            form.password.data,
            form.email.data,
        )
        db.session.add(user)
        db.session.commit()
        flash('User {} successfully added'.format(user))
        return redirect(url_for('index'))

    return render_template('register.html', **{
        'title': 'Registration in app',
        'form': form,
    })


@app.route('/login', methods=['GET', 'POST'])
def login():
    if g.user is not None and g.user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        registered_user = User.query.filter_by(email=form.email.data, password=form.password.data).first()
        if registered_user is None:
            flash('Username or Password is invalid', 'error')
            return redirect(url_for('login'))
        remember_me = False
        if form.remember_me.data:
            remember_me = True
        login_user(registered_user, remember=remember_me)
        flash('Logged in successfully')
        return redirect(request.args.get('next') or url_for('index'))

    return render_template('login.html', **{
        'title': 'Sing In',
        'form': form,
        'providers': app.config['OPENID_PROVIDERS']
    })


@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))


@app.route('/user/<nickname>')
@login_required
def user(nickname):
    user = User.query.filter_by(nickname=nickname).first()
    if user == None:
        flash('User {} not found.'.format(nickname))
        return redirect(url_for('index'))
    posts = [
        { 'author': user, 'body': 'Test post #1' },
        { 'author': user, 'body': 'Test post #2' }
    ]
    return render_template('user.html',
                           user=user,
                           posts=posts)


@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


@app.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block head %}
  {{ super() }}
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
{% endblock %}

{% block scripts %}
  {{ super() }}
  {{ moment.include_moment() }}
  {{ moment.lang('ru') }}
{% endblock %}

{% block title %}
    {% if title %}
        {{title}} - microblog
    {% else %}
        microblog
    {% endif %}
{% endblock %}

{% block navbar %}
    <style>
                body {
      padding-top: 5rem;
    }
    .starter-template {
      padding: 3rem 1.5rem;
      text-align: center;
    }
    </style>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if not current_user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="/login">login <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/registration">Registration</a>
          </li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/logout">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.user', nickname=g.user.nickname) }}">Profile ({{ g.user.nickname }})</a>
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item disabled" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-primary">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block page_content %}
  <h1>Hello, {{ user.nickname }}!</h1>
  <p>Your local time is: {{ moment(current_time).format('LLL') }}</p>
  <p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>
  {% for item in posts %}
      <p>{{ item.author.nickname }} - {{ item.body }}</p>
  {% endfor %}
{% endblock %}

app/templates/register.html
<!-- extend base layout -->
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
    <h1>Register</h1>

    <form action="" method="post" name="register">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ wtf.form_field(form.nickname) }}
        </div>
        <div class="form-group">
            {{ wtf.form_field(form.email) }}
        </div>
        <div class="form-group">
            {{ wtf.form_field(form.password) }}
        </div>
        <div class="form-group">
            {{ wtf.form_field(form.confirm) }}
        </div>
        <button type="submit" class="btn btn-primary">Register me</button>
    </form>
{% endblock %}

app/templates/user.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block page_content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td><h1>User: {{ user.nickname }}</h1></td>
        </tr>
    </table>
    <hr>
    {% for post in posts %}
        <table>
            <tr valign="top">
                <td><img src="{{ post.author.avatar(50) }}"></td><td><i>{{ post.author.nickname }} says:</i><br>{{ post.body }}</td>
            </tr>
        </table>
    {% endfor %}
{% endblock %}